# Generated by Django 3.2.9 on 2022-03-26 14:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=30)),
                ('bookname', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=50)),
                ('book_description', models.CharField(max_length=500, null=True)),
                ('publish_date', models.DateField(default='2022-02-24', max_length=50)),
                ('book_image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='UserInfoForm',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(default='ABC', max_length=300)),
            ],
            options={
                'db_table': 'UserInfoForm',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='bookissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=30)),
                ('bookname', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('publish_date', models.DateField(default='2022-02-24', max_length=50)),
                ('issuedate', models.DateField(max_length=20, null=True)),
                ('returndate', models.DateField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookissue',
            },
        ),
    ]
