# Generated by Django 3.2.9 on 2022-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoform',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
