# Generated by Django 3.2.9 on 2022-03-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinfoform_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='bookid',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='bookissue',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.books'),
        ),
    ]
